version: "2"
services:
  web_server:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo:3.0
    ports:
      - 27017:27017
